name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [syslog-ng-3.25.1,master]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: azure/docker-login@v1
        with:
          login-server: docker.pkg.github.com
          username: ${{ secrets.GitHub_User }}
          password: ${{ secrets.GitHub_PAT }}
      - name: Build for ${{ matrix.version }}
        run: |
          docker build --build-arg BRANCH=${{ matrix.version }} . \
            -t docker.pkg.github.com/splunk/splunk-syslog-ng-container/splunk-syslog-ng-container:${{ github.sha }}
      - name: Push Tag docker.pkg.github.com/splunk/splunk-syslog-ng-container/splunk-syslog-ng-container:${{ github.sha }}
        run: docker push docker.pkg.github.com/splunk/splunk-syslog-ng-container/splunk-syslog-ng-container:${{ github.sha }}

      - name: Push Tag docker.pkg.github.com/splunk/splunk-syslog-ng-container/splunk-syslog-ng-container:${{ matrix.version }}
        run: |
          docker tag docker.pkg.github.com/splunk/splunk-syslog-ng-container/splunk-syslog-ng-container:${{ github.sha }} \
          docker.pkg.github.com/splunk/splunk-syslog-ng-container/splunk-syslog-ng-container:${{ matrix.version }}
          docker push docker.pkg.github.com/splunk/splunk-syslog-ng-container/splunk-syslog-ng-container:${{ matrix.version }}

      - name: Push tag for syslog-ng build
        run: |
          regex='\((.*)\)'
          sv=$(docker run docker.pkg.github.com/splunk/splunk-syslog-ng-container/splunk-syslog-ng-container:${{ github.sha }} --version --rm | head -n 2 | tail -n 1 )
          [[ sv =~ $regex ]]
          docker tag docker.pkg.github.com/splunk/splunk-syslog-ng-container/splunk-syslog-ng-container:${{ github.sha }} \
                      docker.pkg.github.com/splunk/splunk-syslog-ng-container/splunk-syslog-ng-container:${BASH_REMATCH[1]}
          docker push docker.pkg.github.com/splunk/splunk-syslog-ng-container/splunk-syslog-ng-container:${BASH_REMATCH[1]}

