name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        versions: [syslog-ng-3.25.1,master]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: azure/docker-login@v1
        with:
          login-server: contoso.azurecr.io
          username: ${{ secrets.GitHub_User }}
          password: ${{ secrets.GitHub_PAT }}
      - name: Build for ${{ matrix.version }}
        run: |
          docker build --build-arg BRANCH=${{ matrix.version }} . \
            -t docker.pkg.github.com/splunk/splunk-syslog-ng-container/splunk-syslog-ng-container:${{ github.sha }} \
          docker push docker.pkg.github.com/splunk/splunk-syslog-ng-container/splunk-syslog-ng-container:${{ github.sha }}
