name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        versions: [syslog-ng-3.25.1,master]

steps:
  - name: Checkout
    uses: actions/checkout@v1
  - name: Build for ${{ matrix.version }}
    run: docker build --build-arg BRANCH=${{ matrix.version }}
  - name: Dockerize
    if: success()
    uses: manusa/actions-publish-docker@master
    with:
      name: splunk/splunk-syslog-ng-container/splunk-syslog-ng-container
      username: ${{ secrets.GitHub_User }}
      password: ${{ secrets.GitHub_PAT }}
      tag: {{ matrix.version }}
      registry: docker.pkg.github.com
